# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avisoDni.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventDni(object):
    def setupUi(self, ventDni):
        ventDni.setObjectName("ventDni")
        ventDni.resize(423, 178)
        self.label = QtWidgets.QLabel(ventDni)
        self.label.setGeometry(QtCore.QRect(150, 50, 181, 81))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ventDni)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 31, 41))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(ventDni)
        QtCore.QMetaObject.connectSlotsByName(ventDni)

    def retranslateUi(self, ventDni):
        _translate = QtCore.QCoreApplication.translate
        ventDni.setWindowTitle(_translate("ventDni", "Dialog"))
        self.label.setText(_translate("ventDni", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">DNI INCORRECTO</span></p></body></html>"))
        self.label_2.setText(_translate("ventDni", "<html><head/><body><p><img src=\":/avidoDni/warning.jpg\"/></p></body></html>"))
import avisoDni_rc
