# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avisoModificar.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_avisoModificar(object):
    def setupUi(self, avisoModificar):
        avisoModificar.setObjectName("avisoModificar")
        avisoModificar.resize(400, 300)
        self.btnConfirmModificar = QtWidgets.QDialogButtonBox(avisoModificar)
        self.btnConfirmModificar.setGeometry(QtCore.QRect(120, 230, 161, 32))
        self.btnConfirmModificar.setOrientation(QtCore.Qt.Horizontal)
        self.btnConfirmModificar.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnConfirmModificar.setObjectName("btnConfirmModificar")
        self.label = QtWidgets.QLabel(avisoModificar)
        self.label.setGeometry(QtCore.QRect(30, 20, 341, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(avisoModificar)
        self.label_2.setGeometry(QtCore.QRect(170, 90, 61, 61))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(avisoModificar)
        self.btnConfirmModificar.accepted.connect(avisoModificar.accept)
        self.btnConfirmModificar.rejected.connect(avisoModificar.reject)
        QtCore.QMetaObject.connectSlotsByName(avisoModificar)

    def retranslateUi(self, avisoModificar):
        _translate = QtCore.QCoreApplication.translate
        avisoModificar.setWindowTitle(_translate("avisoModificar", "Dialog"))
        self.label.setText(_translate("avisoModificar", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">¿Seguro que quieres modificar el cliente ?</span></p></body></html>"))
        self.label_2.setText(_translate("avisoModificar", "<html><head/><body><p><img src=\":/avisomod/avisos1.jpg\"/></p></body></html>"))
import avisomod_rc
