# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avisoModificarProd.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_avisoModificarProd(object):
    def setupUi(self, avisoModificarProd):
        avisoModificarProd.setObjectName("avisoModificarProd")
        avisoModificarProd.resize(400, 300)
        self.btnConfirmModificar = QtWidgets.QDialogButtonBox(avisoModificarProd)
        self.btnConfirmModificar.setGeometry(QtCore.QRect(120, 230, 161, 32))
        self.btnConfirmModificar.setOrientation(QtCore.Qt.Horizontal)
        self.btnConfirmModificar.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnConfirmModificar.setObjectName("btnConfirmModificar")
        self.label = QtWidgets.QLabel(avisoModificarProd)
        self.label.setGeometry(QtCore.QRect(30, 20, 341, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(avisoModificarProd)
        self.label_2.setGeometry(QtCore.QRect(170, 90, 61, 61))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(avisoModificarProd)
        self.btnConfirmModificar.accepted.connect(avisoModificarProd.accept)
        self.btnConfirmModificar.rejected.connect(avisoModificarProd.reject)
        QtCore.QMetaObject.connectSlotsByName(avisoModificarProd)

    def retranslateUi(self, avisoModificarProd):
        _translate = QtCore.QCoreApplication.translate
        avisoModificarProd.setWindowTitle(_translate("avisoModificarProd", "Dialog"))
        self.label.setText(_translate("avisoModificarProd", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">¿Seguro que quieres modificar el producto ?</span></p></body></html>"))
        self.label_2.setText(_translate("avisoModificarProd", "<html><head/><body><p><img src=\":/avisomod/avisos1.jpg\"/></p></body></html>"))
import avisomod_rc
