# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avisoEliminar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_avisoEliminar(object):
    def setupUi(self, avisoEliminar):
        avisoEliminar.setObjectName("avisoEliminar")
        avisoEliminar.resize(400, 300)
        self.label_2 = QtWidgets.QLabel(avisoEliminar)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 331, 31))
        self.label_2.setObjectName("label_2")
        self.aviso = QtWidgets.QLabel(avisoEliminar)
        self.aviso.setGeometry(QtCore.QRect(160, 100, 71, 71))
        self.aviso.setObjectName("aviso")
        self.btnConfirmBorrar = QtWidgets.QDialogButtonBox(avisoEliminar)
        self.btnConfirmBorrar.setGeometry(QtCore.QRect(110, 210, 156, 23))
        self.btnConfirmBorrar.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnConfirmBorrar.setObjectName("btnConfirmBorrar")

        self.retranslateUi(avisoEliminar)
        QtCore.QMetaObject.connectSlotsByName(avisoEliminar)

    def retranslateUi(self, avisoEliminar):
        _translate = QtCore.QCoreApplication.translate
        avisoEliminar.setWindowTitle(_translate("avisoEliminar", "Dialog"))
        self.label_2.setText(_translate("avisoEliminar", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Seguro que queires eliminar el cliente ?</span></p></body></html>"))
        self.aviso.setText(_translate("avisoEliminar", "<html><head/><body><p><img src=\":/avisoEliminar/advertencia.png\"/></p></body></html>"))
import avisoEliminar_rc
