# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avisoImportar.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaImportar(object):
    def setupUi(self, ventanaImportar):
        ventanaImportar.setObjectName("ventanaImportar")
        ventanaImportar.resize(400, 300)
        ventanaImportar.setModal(True)
        self.buttonBoxImportar = QtWidgets.QDialogButtonBox(ventanaImportar)
        self.buttonBoxImportar.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBoxImportar.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxImportar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxImportar.setCenterButtons(True)
        self.buttonBoxImportar.setObjectName("buttonBoxImportar")
        self.label = QtWidgets.QLabel(ventanaImportar)
        self.label.setGeometry(QtCore.QRect(30, 39, 351, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ventanaImportar)
        self.label_2.setGeometry(QtCore.QRect(170, 100, 61, 71))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(ventanaImportar)
        self.buttonBoxImportar.accepted.connect(ventanaImportar.accept)
        self.buttonBoxImportar.rejected.connect(ventanaImportar.reject)
        QtCore.QMetaObject.connectSlotsByName(ventanaImportar)

    def retranslateUi(self, ventanaImportar):
        _translate = QtCore.QCoreApplication.translate
        ventanaImportar.setWindowTitle(_translate("ventanaImportar", "Dialog"))
        self.label.setText(_translate("ventanaImportar", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Seguro que desea importar los datos ?</span></p></body></html>"))
        self.label_2.setText(_translate("ventanaImportar", "<html><head/><body><p><img src=\":/avisoImportar/avisos1.jpg\"/></p></body></html>"))
import avisoImportar_rc
