# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventSalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventSalir(object):
    def setupUi(self, ventSalir):
        ventSalir.setObjectName("ventSalir")
        ventSalir.resize(399, 160)
        ventSalir.setModal(True)
        self.btnBoxSalir = QtWidgets.QDialogButtonBox(ventSalir)
        self.btnBoxSalir.setGeometry(QtCore.QRect(150, 90, 161, 32))
        self.btnBoxSalir.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxSalir.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxSalir.setCenterButtons(False)
        self.btnBoxSalir.setObjectName("btnBoxSalir")
        self.label = QtWidgets.QLabel(ventSalir)
        self.label.setGeometry(QtCore.QRect(80, 20, 311, 51))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lblImgAviso = QtWidgets.QLabel(ventSalir)
        self.lblImgAviso.setGeometry(QtCore.QRect(20, 20, 47, 41))
        self.lblImgAviso.setText("")
        self.lblImgAviso.setPixmap(QtGui.QPixmap(":/avisosalir/warning.jpg"))
        self.lblImgAviso.setObjectName("lblImgAviso")

        self.retranslateUi(ventSalir)
        self.btnBoxSalir.accepted.connect(ventSalir.accept)
        self.btnBoxSalir.rejected.connect(ventSalir.reject)
        QtCore.QMetaObject.connectSlotsByName(ventSalir)

    def retranslateUi(self, ventSalir):
        _translate = QtCore.QCoreApplication.translate
        ventSalir.setWindowTitle(_translate("ventSalir", "Desea salir ?"))
        self.label.setText(_translate("ventSalir", "<html><head/><body><p><span style=\" font-size:10pt;\">¿ Está seguro que desea salir de la aplicación ?</span></p></body></html>"))
import avisosalir_rc
