# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentCalendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentCalendar(object):
    def setupUi(self, VentCalendar):
        VentCalendar.setObjectName("VentCalendar")
        VentCalendar.resize(396, 292)
        self.Calendar = QtWidgets.QCalendarWidget(VentCalendar)
        self.Calendar.setEnabled(True)
        self.Calendar.setGeometry(QtCore.QRect(0, 0, 401, 291))
        self.Calendar.setObjectName("Calendar")

        self.retranslateUi(VentCalendar)
        QtCore.QMetaObject.connectSlotsByName(VentCalendar)

    def retranslateUi(self, VentCalendar):
        _translate = QtCore.QCoreApplication.translate
        VentCalendar.setWindowTitle(_translate("VentCalendar", "Calendario"))
