# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventAviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventAviso(object):
    def setupUi(self, ventAviso):
        ventAviso.setObjectName("ventAviso")
        ventAviso.resize(399, 160)
        ventAviso.setModal(True)
        self.btnBoxSalir = QtWidgets.QDialogButtonBox(ventAviso)
        self.btnBoxSalir.setGeometry(QtCore.QRect(150, 90, 161, 32))
        self.btnBoxSalir.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxSalir.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxSalir.setCenterButtons(False)
        self.btnBoxSalir.setObjectName("btnBoxSalir")
        self.lblImgAviso = QtWidgets.QLabel(ventAviso)
        self.lblImgAviso.setGeometry(QtCore.QRect(20, 20, 47, 41))
        self.lblImgAviso.setText("")
        self.lblImgAviso.setPixmap(QtGui.QPixmap(":/avisosalir/warning.jpg"))
        self.lblImgAviso.setObjectName("lblImgAviso")

        self.retranslateUi(ventAviso)
        self.btnBoxSalir.accepted.connect(ventAviso.accept)
        self.btnBoxSalir.rejected.connect(ventAviso.reject)
        QtCore.QMetaObject.connectSlotsByName(ventAviso)

    def retranslateUi(self, ventAviso):
        _translate = QtCore.QCoreApplication.translate
        ventAviso.setWindowTitle(_translate("ventAviso", "Desea salir ?"))
import avisosalir_rc
